version: "3.8"
services:
  frontend:
    build:
      context: ./frontend/react-app 
    ports:
      - "5173:5173" 
    env_file:
      - .env    # Load environment variables from .env
    networks:
      - react-test
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5050:5050"
    env_file:
      - .env      
    networks:
      - react-test

networks:
  react-test:
    
