# Use Node.js LTS as the base image
FROM node:latest

# Set the working directory in the container
WORKDIR /node

# Copy package.json and package-lock.json
COPY package.json .

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port 
EXPOSE 5050

# Define the command to run the app
CMD ["npm", "start"]
