# Use Node.js LTS as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /node

# Copy package.json and package-lock.json
COPY package.json .

# Install dependencies
RUN npm install && npm install react-chat-widget --legacy-peer-deps


# Copy the rest of the application code
COPY . .

# Expose the port 
EXPOSE 5173

# Define the command to run the app
CMD ["npm", "run","dev"]
